version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      # TypeScript ecosystem and type definitions
      typescript:
        patterns:
          - "typescript"
          - "@tsd/typescript"
          - "@types/*"
          - "@typescript-eslint/*"
      
      # ESLint and linting tools
      eslint:
        patterns:
          - "eslint*"
          - "@stylistic/eslint-plugin-ts"
          - "@grafana/eslint-config"
      
      # Build and development tools
      build-tools:
        patterns:
          - "@swc/*"
          - "@swc-node/*"
          - "vitest"
          - "nodemon"
          - "npm-run-all"
          - "prettier"
      
      # CLI utilities and core tools
      cli-utilities:
        patterns:
          - "chalk"
          - "debug"
          - "ora"
          - "yargs"
          - "execa"
          - "fast-glob"
          - "node-fetch"
          - "tar"
          - "diff"
          - "tty-table"
      
      # Grafana packages
      grafana:
        patterns:
          - "@grafana/*"
