import { GrafanaTheme2 } from '@grafana/data';
export declare const getTableStyles: (theme: GrafanaTheme2) => {
    theme: GrafanaTheme2;
    cellHeight: number;
    buildCellContainerStyle: (color?: string | undefined, background?: string | undefined) => string;
    cellPadding: number;
    lastChildExtraPadding: number;
    cellHeightInner: number;
    rowHeight: number;
    table: string;
    thead: string;
    tfoot: string;
    headerCell: string;
    headerCellLabel: string;
    cellContainer: string;
    cellText: string;
    cellLink: string;
    imageCellLink: string;
    headerFilter: string;
    row: string;
    imageCell: string;
    resizeHandle: string;
    filterWrapper: string;
    filterItem: string;
    typeIcon: string;
    noData: string;
};
export declare type TableStyles = ReturnType<typeof getTableStyles>;
