name: 'Levitate is compatible'
description: 'Check if your plugin code is compatible with grafana latest APIs'

inputs:
  module:
    required: true
    description: 'Path to your plugin module.ts file'
runs:
  using: 'composite'
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: run-levitate
      run: |
        # RUN levitate is-compatible
        npx --yes @grafana/levitate@latest is-compatible --path ${{ inputs.module }} --target @grafana/data,@grafana/ui,@grafana/runtime | tee .levitate_output
        CODE=${PIPESTATUS[0]}
        IS_COMPATIBLE=$(cat .levitate_output)
        # 
        IS_COMPATIBLE="${IS_COMPATIBLE//'%'/'%25'}"
        IS_COMPATIBLE="${IS_COMPATIBLE//$'\n'/'%0A'}"
        IS_COMPATIBLE="${IS_COMPATIBLE//$'\r'/'%0D'}"
        echo "::set-output name=is-compatible-stdout::$IS_COMPATIBLE"
        echo "::set-output name=is-compatible-exit-code::$CODE"

      shell: "bash"
    - uses: jwalton/gh-find-current-pr@e12d66bc9ecc4fdcde07b0f70a3cb68ce7e4d807
      id: finder
    - uses: marocchino/sticky-pull-request-comment@e3c0353c9ad3f0cad0fbab901e5bcd7d04c6e97b
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: |
          Levitate is-compatible report:

          ${{ steps.run-levitate.outputs.is-compatible-stdout }}
