name: 'Hello World'
description: 'Greet someone and record the time'

outputs:
  random:
    description: 'no idea'
    value: ${{ steps.run-levitate.outputs.is-compatible-out}}
inputs:
  module:
    required: true
    description: 'Path to your plugin module.ts file'
runs:
  using: 'composite'
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: run-levitate
      run: |
        echo "::set-output name=is-compatible-out::$(npx --yes @grafana/levitate@latest is-compatible --path ${{ inputs.module }} --target @grafana/data)"
      shell: "bash"
    - run: echo "${{ steps.run-levitate.outputs.is-compatible-out }}"
      shell: "bash"
