name: 'Levitate is compatible'
description: 'Check if your plugin code is compatible with grafana latest APIs'

outputs:
  is-compatible-stdout:
    description: 'Standard output from running levitate is-compatible command against the module'
    value: ${{ steps.run-levitate.outputs.is-compatible-stdout}}
inputs:
  module:
    required: true
    description: 'Path to your plugin module.ts file'
runs:
  using: 'composite'
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: run-levitate
      run: |
        echo "::set-output name=is-compatible-stdout::$(npx --yes @grafana/levitate@latest is-compatible --path ${{ inputs.module }} --target @grafana/data,@grafana/ui,@grafana/runtime,@grafana/schema | cat)"
      shell: "bash"
    - run: echo "${{ steps.run-levitate.outputs.is-compatible-stdout }}"
      shell: "bash"
    - uses: jwalton/gh-find-current-pr@v1
      id: finder
    - uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: |
          Levitate is-compatible report:

          ${{ steps.run-levitate.outputs.is-compatible-stdout }}
