name: 'Levitate is compatible'
description: 'Check if your plugin code is compatible with grafana latest APIs'

inputs:
  module:
    required: true
    description: 'Path to your plugin module.ts file'
runs:
  using: 'composite'
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: run-levitate
      run: |
        # echo "::set-output name=is-compatible-stdout::$(npx --yes @grafana/levitate@latest is-compatible --path ${{ inputs.module }} --target @grafana/data,@grafana/ui,@grafana/runtime,@grafana/schema | cat)"
        IS_COMPATIBLE=$(npx --yes @grafana/levitate@latest is-compatible --path ${{ inputs.module }} --target @grafana/data,@grafana/ui,@grafana/runtime,@grafana/schema)
        IS_COMPATIBLE="${IS_COMPATIBLE//'%'/'%25'}"
        IS_COMPATIBLE="${IS_COMPATIBLE//$'\n'/'%0A'}"
        IS_COMPATIBLE="${IS_COMPATIBLE//$'\r'/'%0D'}"
        echo "::set-output name=is-compatible-stdout::$IS_COMPATIBLE"

      shell: "bash"
    - run: echo "${{ steps.run-levitate.outputs.is-compatible-stdout }}"
      shell: "bash"
    - name: Test
      uses: actions/github-script@v6
      with:
        script: |
          const core = require('@actions/core')
          const prNumber = context.payload.number;
          core.exportVariable('PULL_NUMBER', prNumber);
    - uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        number: ${{ env.PULL_NUMBER }}
        message: |
          Levitate is-compatible report:

          ${{ steps.run-levitate.outputs.is-compatible-stdout }}
