name: CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Automated checks
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint files
        run: yarn lint

      - name: Run knip
        run: yarn knip:ci

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build
