name: metrics-to-bigquery
on: [push]

  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 */2 * * *'
env:
  BQ_SA_KEY: '${{ secrets.BQ_SA_KEY }}'
  BQ_PROJECT: '${{ secrets.BQ_PROJECT }}'
  BQ_DATASET: 'plugins_data'
  BQ_TABLE: 'grafana_imports'

jobs:
  build:
    name: run-levitate-on-gcom-plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install @google-cloud/bigquery axios @grafana/levitate @grafana/levitate-bq
      
      - name: Find plugins to levitate
        id: plugins-to-levitate
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/workflows/scripts/plugins-to-levitate.js');
            await script();

      - name: Levitate plugins
        uses: actions/github-script@v5
        env:
          PLUGINS_FILE_PATH: '${{ steps.plugins-to-levitate.outputs.result }}'
        with:
          script: |
            const script = require('./.github/workflows/scripts/levitate-plugins.js');
            await script({ core, exec });