name: metrics-to-bigquery
on: [push]

  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 */2 * * *'

jobs:
  build:
    name: run-levitate-on-gcom-plugins
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install @google-cloud/bigquery axios
      
      - name: Find plugins to levitate
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/workflows/scripts/metrics-to-bq.js');
            const options = {
              credentials: JSON.parse('${{ secrets.BQ_SA_KEY }}'),
              projectId: '${{ secrets.BQ_PROJECT }}'
            };

            await script({context, core, options});