name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: grafana-plugins-platform-bot
          permission_set: npm-bump-version

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: false

      - name: Setup environment
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --immutable

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
