name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@a37de51f3d713a30a9e4b21bcdfbd38170020593 # v1.3.0
        with:
          repo_secrets: |
            GITHUB_APP_ID=plugins-platform-bot-app:app_id
            GITHUB_APP_PRIVATE_KEY=plugins-platform-bot-app:app_pem
          export_env: false

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate_token
        with:
          app-id: ${{ fromJSON(steps.get-secrets.outputs.secrets).GITHUB_APP_ID }}
          private-key: ${{ fromJSON(steps.get-secrets.outputs.secrets).GITHUB_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: googleapis/release-please-action@0dfd8538845b8e92600d271a895a5372865d4062 # v5.0.0
        id: release
        with:
          token: ${{ steps.generate_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: false

      - name: Setup environment
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --immutable

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
