on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check compatibility
        id: levitate
        uses: grafana/levitate/actions/is-compatible@levitate-action-comment
        with:
          module: "./src/bin.ts"
          comment-pr: 'yes'
          fail-if-incompatible: 'yes'
